"""empty message

Revision ID: d70c058ab35f
Revises: d8cd111ce992
Create Date: 2026-02-06 18:56:38.489715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70c058ab35f'
down_revision = 'd8cd111ce992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_technical_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('collection', sa.String(length=120), nullable=True),
    sa.Column('anime_series', sa.String(length=200), nullable=True),
    sa.Column('character', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_technical_details')
    # ### end Alembic commands ###
